[mypy]
explicit_package_bases = True
mypy_path = .

# Third-party libraries without stubs
[mypy-torch_directml.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-term_image.*]
ignore_missing_imports = True

[mypy-mypyc.*]
follow_untyped_imports = True